# Homebrew Bundle
# Install everything with: brew bundle
# Note: MSSQL tools are installed separately in install-apps.sh due to interactive EULA prompts

# Formulae
brew "mongodb-database-tools"
brew "mongosh"
brew "ripgrep"
brew "jq"
brew "yq"

# Casks
cask "android-studio"
cask "apidog"
cask "bitwarden"
cask "brave-browser"
cask "cleanshot"
cask "cold-turkey-blocker"
cask "copilot-cli"
cask "datagrip"
cask "devin-cli"
cask "displaylink"
cask "docker-desktop"
cask "firefox"
cask "freelens"
cask "keepingyouawake"
cask "microsoft-excel"
cask "microsoft-outlook"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "microsoft-word"
cask "notion"
cask "postman"
cask "raycast"
cask "rectangle"
cask "redis-insight"
cask "rider"
cask "slack"
cask "snowflake-cli"
cask "snowflake-snowsql"
cask "spotify"
cask "studio-3t"
cask "sublime-merge"
cask "sublime-text"
cask "tabby"
cask "telegram"
cask "the-unarchiver"
cask "utm"
cask "visual-studio-code"
cask "webstorm"
cask "zoom"
