#!/usr/bin/env zsh

local sort_by="name"
local signal="15"
zparseopts -D -- n=arg_n m=arg_m c=arg_c
if (( $#arg_n )); then sort_by="name"; fi
if (( $#arg_m )); then sort_by="mem"; fi
if (( $#arg_c )); then sort_by="cpu"; fi
if [[ -n "$1" ]]; then signal="$1"; fi

case "$sort_by" in
  mem)
    ps -u $USER -o pid,pcpu,pmem,comm -m \
      | awk 'NR>1{n=split($4,a,"/"); $4=a[n]; print $1"\t"$2"\t"$3"\t"$4}' \
      | fzf --header='PID  CPU% MEM% COMMAND' \
      | awk '{print $1}' | xargs -r kill -$signal
    ;;
  cpu)
    ps -u $USER -o pid,pcpu,pmem,comm -r \
      | awk 'NR>1{n=split($4,a,"/"); $4=a[n]; print $1"\t"$2"\t"$3"\t"$4}' \
      | fzf --header='PID  CPU% MEM% COMMAND' \
      | awk '{print $1}' | xargs -r kill -$signal
    ;;
  name)
    ps -u $USER -o pid,pcpu,pmem,comm \
      | awk 'NR>1{n=split($4,a,"/"); $4=a[n]; print $1"\t"$2"\t"$3"\t"$4}' \
      | sort -k4 \
      | fzf --header='PID  CPU% MEM% COMMAND' \
      | awk '{print $1}' | xargs -r kill -$signal
    ;;
esac
