version: 7
profiles:
  - type: local
    name: Repos
    options:
      restoreFromPTYID: null
      command: /bin/zsh
      args:
        - '--login'
      cwd: /Users/terryschneider/Repos
      env: {}
      width: null
      height: null
      pauseAfterExit: false
      runAsAdministrator: false
    id: local:custom:OS-default:fa7c1f7c-6c73-4fdf-bb7d-eda6cff279a0
    group: ''
    icon: ''
    color: ''
    disableDynamicTitle: false
    behaviorOnSessionEnd: auto
  - id: split-layout:custom:WMT-CT-Backend:18d5afad-7e5a-4e83-ae6e-73248c7e6973
    type: split-layout
    name: WMT CT Backend
    options:
      recoveryToken:
        type: app:split-tab
        ratios:
          - 0.5
          - 0.5
        orientation: h
        children:
          - type: app:split-tab
            ratios:
              - 0.3333333333333333
              - 0.3333333333333333
              - 0.3333333333333333
            orientation: v
            children:
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Docker
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: /Users/terryschneider/Repos/ct/ct-developers
                    env:
                      STARTCMD: docker compose up
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Backend
                tabCustomTitle: ''
                disableDynamicTitle: false
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Web
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: >-
                      /Users/terryschneider/Repos/ct/controltower/TrailerTracking/TrailerTracking.Web
                    env:
                      STARTCMD: yarn start
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Backend
                tabCustomTitle: ''
                disableDynamicTitle: false
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Worker
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: >-
                      /Users/terryschneider/Repos/ct/controltower/TrailerTracking/TrailerTracking.Worker
                    env:
                      STARTCMD: dotnet watch run
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Backend
                tabCustomTitle: ''
                disableDynamicTitle: false
          - type: app:split-tab
            ratios:
              - 0.3333333333333333
              - 0.3333333333333333
              - 0.3333333333333333
            orientation: v
            children:
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Module Core
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: >-
                      /Users/terryschneider/Repos/ct/ct-modules/module-web/apps/ct-core
                    env:
                      STARTCMD: ng serve --host 0.0.0.0 --port 4200
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Backend
                tabCustomTitle: ''
                disableDynamicTitle: false
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Module Web
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: >-
                      /Users/terryschneider/Repos/ct/ct-modules/module-core/Core.Api
                    env:
                      STARTCMD: dotnet run
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Backend
                tabCustomTitle: ''
                disableDynamicTitle: false
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Tests
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: >-
                      /Users/terryschneider/Repos/ct/controltower/TrailerTracking/TrailerTracking.Test
                    env: {}
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Backend
                tabCustomTitle: ''
                disableDynamicTitle: false
  - id: split-layout:custom:WMT-CT-Mobile:d19c310a-a642-4d91-a62a-e1811053d7ce
    type: split-layout
    name: WMT CT Mobile
    options:
      recoveryToken:
        type: app:split-tab
        ratios:
          - 0.5
          - 0.5
        orientation: h
        children:
          - type: app:split-tab
            ratios:
              - 0.5
              - 0.5
            orientation: v
            children:
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: Build API Client
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: >-
                      /Users/terryschneider/Repos/ct/controltowermobile/src/ControlTowerMobile.Api.Client
                    env:
                      STARTCMD: ./nswag-build.sh
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Mobile
                disableDynamicTitle: false
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Mobile
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: /Users/terryschneider/Repos/ct/controltowermobile
                    env: {}
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Mobile
                tabCustomTitle: ''
                disableDynamicTitle: false
          - type: app:split-tab
            ratios:
              - 0.5
              - 0.5
            orientation: v
            children:
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Developers
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: /Users/terryschneider/Repos/ct/ct-developers
                    env: {}
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Mobile
                tabCustomTitle: ''
                disableDynamicTitle: false
              - type: app:local-tab
                profile:
                  id: local:default
                  type: local
                  name: WMT CT Mobile Tests
                  group: ''
                  options:
                    restoreFromPTYID: false
                    command: /bin/zsh
                    args:
                      - '--login'
                    cwd: >-
                      /Users/terryschneider/Repos/ct/ControlTowerMobile/src/ControlTowerMobile.Tests
                    env: {}
                    width: null
                    height: null
                    pauseAfterExit: false
                    runAsAdministrator: false
                  icon: ''
                  color: ''
                  disableDynamicTitle: false
                  weight: 0
                  isBuiltin: true
                  isTemplate: false
                  terminalColorScheme: null
                  behaviorOnSessionEnd: auto
                savedState: false
                tabTitle: WMT CT Mobile
                tabCustomTitle: ''
                disableDynamicTitle: false
configSync:
  parts: {}
hotkeys:
  toggle-window:
    - ⌘-Shift-C
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-line:
    - ⌘-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  focus-all-tabs:
    - ⌘-⌥-Shift-I
  scroll-to-top:
    - Shift-PageUp
  scroll-up:
    - ⌥-PageUp
  scroll-down:
    - ⌥-PageDown
  scroll-to-bottom:
    - Shift-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - ⌘-T
  new-window:
    - ⌘-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - Ctrl-Shift
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - ⌘-Shift-.
  combine-tabs:
    - ⌘-Shift-,
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-Shift-W
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
  command-selector:
    - ⌘-Shift-P
  group-selectors: {}
terminal:
  searchOptions: {}
  colorScheme:
    name: Afterglow
    foreground: '#d0d0d0'
    background: '#212121'
    cursor: '#d0d0d0'
    colors:
      - '#151515'
      - '#ac4142'
      - '#7e8e50'
      - '#e5b567'
      - '#6c99bb'
      - '#9f4e85'
      - '#7dd6cf'
      - '#d0d0d0'
      - '#505050'
      - '#ac4142'
      - '#7e8e50'
      - '#e5b567'
      - '#6c99bb'
      - '#9f4e85'
      - '#7dd6cf'
      - '#f5f5f5'
  font: Fira Code
  customColorSchemes: []
  cursor: beam
  autoOpen: false
  showRecentProfiles: 0
  profile: local:custom:OS-default:fa7c1f7c-6c73-4fdf-bb7d-eda6cff279a0
  fontSize: 12
ssh: {}
clickableLinks: {}
accessibility: {}
appearance:
  vibrancy: true
  tabsLocation: right
  frame: full
hacks: {}
providerBlacklist: []
commandBlacklist: []
language: en-US
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
groups: []
recoverTabs: false
