- name: Repos
  tabs:
    - title: Repos
      profile: Repos
- name: CPW
  tabs:
    - title: Platform Docker
      profile: Platform Docker
    - title: Platform
      profile: Platform
    - title: CPW
      profile: CPW
    - title: CPW UI
      profile: CPW UI
    - title: Repos
      profile: Repos
- name: WMT CT
  tabs:
    - title: WMT CT Backend
      profile: WMT CT Backend
    - title: WMT CT Mobile
      profile: WMT CT Mobile
    - title: Repos
      profile: Repos
